from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.sql import text
from sqlmodel import SQLModel

from app.config import settings

# Create a database engine to connect with database
engine = create_async_engine(
    # database type/dialect and file name
    url=settings.POSTGRES_URL,
    # Log sql queries
    echo=True,
)

async_session_factory = sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


async def create_db_tables():
    async with engine.begin() as connection:
        from app.database.models import Seller, Shipment  # noqa: F401

        await connection.run_sync(SQLModel.metadata.create_all)

        # Handle legacy seller schema from older runs.
        has_password_hased = await connection.scalar(
            text(
                """
                SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'seller' AND column_name = 'password_hased'
                )
                """
            )
        )
        has_password_hash = await connection.scalar(
            text(
                """
                SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'seller' AND column_name = 'password_hash'
                )
                """
            )
        )

        if has_password_hased and not has_password_hash:
            await connection.execute(
                text("ALTER TABLE seller RENAME COLUMN password_hased TO password_hash")
            )

        seller_id_is_identity = await connection.scalar(
            text(
                """
                SELECT is_identity
                FROM information_schema.columns
                WHERE table_name = 'seller' AND column_name = 'id'
                """
            )
        )

        if seller_id_is_identity != "YES":
            await connection.execute(
                text(
                    "ALTER TABLE seller ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
                )
            )


async def get_session():
    async with async_session_factory() as session:
        yield session
