"""added the delivery partner

Revision ID: 21d5683dcf9f
Revises: af4b388ef72c
Create Date: 2026-04-05 15:58:12.931241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "21d5683dcf9f"
down_revision: Union[str, Sequence[str], None] = "af4b388ef72c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_partner",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("serviceable_zip_codes", sa.ARRAY(sa.INTEGER()), nullable=True),
        sa.Column("max_haldeling_capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "seller", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True)
    )
    op.drop_column("seller", "address")
    op.add_column(
        "shipment", sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True)
    )
    # Step 1: Add delivery_partner_id as NULLABLE to avoid constraint violation on existing rows
    op.add_column(
        "shipment", sa.Column("delivery_partner_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None, "shipment", "delivery_partner", ["delivery_partner_id"], ["id"]
    )
    # Note: The column is kept as nullable because:
    # 1. Existing shipments may not have a delivery partner assigned yet
    # 2. No delivery partners may exist in the database at migration time
    # 3. Enforce NOT NULL constraint at application/model level instead


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shipment", type_="foreignkey")  # type: ignore
    op.drop_column("shipment", "delivery_partner_id")
    op.drop_column("shipment", "created_at")
    op.add_column(
        "seller",
        sa.Column(
            "address",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("seller", "created_at")
    op.drop_table("delivery_partner")
    # ### end Alembic commands ###
