"""Added user verified email

Revision ID: 0aae654a4a14
Revises: 3_fix_phone_column_type
Create Date: 2026-04-09 16:11:45.252533

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aae654a4a14'
down_revision: Union[str, Sequence[str], None] = '3_fix_phone_column_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add columns as nullable so existing rows aren't rejected
    op.add_column('delivery_partner', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('seller', sa.Column('email_verified', sa.Boolean(), nullable=True))

    # Step 2: Backfill existing rows with a default value of False
    op.execute("UPDATE delivery_partner SET email_verified = FALSE WHERE email_verified IS NULL")
    op.execute("UPDATE seller SET email_verified = FALSE WHERE email_verified IS NULL")

    # Step 3: Now apply the NOT NULL constraint
    op.alter_column('delivery_partner', 'email_verified', nullable=False)
    op.alter_column('seller', 'email_verified', nullable=False)

    # Backfill shipment email NULLs before enforcing NOT NULL
    op.execute("UPDATE shipment SET client_contact_email = '' WHERE client_contact_email IS NULL")
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # Backfill shipment phone NULLs before casting VARCHAR -> BigInteger
    op.execute("UPDATE shipment SET client_contact_phone = '0' WHERE client_contact_phone IS NULL")
    op.alter_column('shipment', 'client_contact_phone',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               postgresql_using='client_contact_phone::bigint',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'client_contact_phone',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('seller', 'email_verified')
    op.drop_column('delivery_partner', 'email_verified')
    # ### end Alembic commands ###
