"""Added the shipmentevent

Revision ID: a3c854a4cc78
Revises: 21d5683dcf9f
Create Date: 2026-04-07 09:54:02.734527

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a3c854a4cc78"
down_revision: Union[str, Sequence[str], None] = "21d5683dcf9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipmentevent",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("location", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="shipmentstatus", create_type=False),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "seller",
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("seller", sa.Column("zip_code", sa.Integer(), nullable=True))

    # Data migration: Update existing NULL delivery_partner_id values
    # Get the first delivery partner ID to use as default, or generate a new one
    connection = op.get_bind()
    existing_null_shipments = connection.execute(
        sa.text("SELECT COUNT(*) FROM shipment WHERE delivery_partner_id IS NULL")
    ).scalar()

    if existing_null_shipments > 0:
        # Get the first delivery partner, or create a placeholder
        first_partner = connection.execute(
            sa.text("SELECT id FROM delivery_partner LIMIT 1")
        ).scalar()

        if first_partner:
            connection.execute(
                sa.text(
                    "UPDATE shipment SET delivery_partner_id = :partner_id WHERE delivery_partner_id IS NULL"
                ),
                {"partner_id": first_partner},
            )

    # Now set the NOT NULL constraint
    op.alter_column(
        "shipment", "delivery_partner_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_foreign_key(
        None, "shipment", "delivery_partner", ["delivery_partner_id"], ["id"]
    )
    op.drop_column("shipment", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shipment",
        sa.Column(
            "status",
            postgresql.ENUM(
                "placed",
                "in_transit",
                "out_for_delivery",
                "delivered",
                name="shipmentstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "shipment", type_="foreignkey")
    op.alter_column(
        "shipment", "delivery_partner_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_column("seller", "zip_code")
    op.drop_column("seller", "address")
    op.drop_table("shipmentevent")
    # ### end Alembic commands ###
